### ISSUE TITLE
Update to KEDA 2.0

### ISSUE THREAD

**Issue by jeffhollan** [balchua/gonuts#2]
We'll be updating the [KEDA Samples README](https://github.com/kedacore/samples) to call out which samples only work with KEDA 1.0.  It looks like you'd need changes to make this 2.0 compatible (in deployment), so creating issue here to call out.  Here's a link to the migration guide for 2.0 https://keda.sh/docs/2.0/migration/

Thanks regardless for this sample!

**Comment by balchua** [comment]
Thanks @jeffhollan for the heads up. Will updating the sample soon.👍

**Comment by balchua** [comment]
Thanks @jeffhollan i have updated the sample to use Keda v2.
